# basic_eager_api

In [21]:
from __future__ import absolute_import, division, print_function
import numpy as np
import tensorflow as tf
import tensorflow.contrib.eager as tfe

In [22]:
# Set Eager API

print("Setting Eager mode...")

tfe.enable_eager_execution()

Setting Eager mode...


In [23]:
# Define constant tensors

print("Define constant tensors")

a = tf.constant(2)

print("a = %i" % a)

b = tf.constant(3)

print("b = %i" % b)

Define constant tensors
a = 2
b = 3


In [24]:
a = tf.constant(6)
print("a= %i"% a)

a= 6


In [25]:
a = 5

In [26]:
print("a= %i" %a)

a= 5


In [27]:
# Run the operation without the need for tf.Session

print("Running operations, without tf.Session")

c = a + b

print("a + b = %i" % c)

d = a * b

print("a * b = %i" % d)

Running operations, without tf.Session
a + b = 8
a * b = 15


In [28]:
# Full compatibility with Numpy

print("Mixing operations with Tensors and Numpy Arrays")
# Define constant tensors
a = tf.constant([[2., 1.],

                 [1., 0.]], dtype=tf.float32)

print("Tensor:\n a = %s" % a)
b = np.array([[3., 0.],

              [5., 1.]], dtype=np.float32)

print("NumpyArray:\n b = %s" % b)

Mixing operations with Tensors and Numpy Arrays
Tensor:
 a = tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
NumpyArray:
 b = [[3. 0.]
 [5. 1.]]


In [29]:
c = tf.constant([[1,2,3],[4,5,6]])
print("Tensor:\n c = %s" % c)

Tensor:
 c = tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [30]:
c = np.reshape(c,-1,1)
print("Tensor:\n c = %s" % c)

Tensor:
 c = [1 4 2 5 3 6]


In [31]:
d = tf.matmul(a, b)
print("a * b = %s" % d)

print("Iterate through Tensor 'a':")
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

a * b = tf.Tensor(
[[11.  1.]
 [ 3.  0.]], shape=(2, 2), dtype=float32)
Iterate through Tensor 'a':
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
